# KafkaTest

###
# @name SendMessage
POST http://localhost:8080/send
Content-Type: application/json

{
  "to": "username",
  "text": "Message text!"
}

###
# @name Register new user
POST http://localhost:8080/auth/register
accept: */*
Content-Type: application/json

{
  "username": "username",
  "password": "Password"
}

###
# @name Log in
POST http://localhost:8080/auth/login
accept: */*
Content-Type: application/json

{
  "username": "username",
  "password": "Password"
}